import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f5f7fb" },
  container: { flex: 1, padding: 20, justifyContent: "center" },
  card: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 20,
    shadowColor: "#0a0a0a",
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 6,
  },
  headerRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  logo: {
    width: 64,
    height: 64,
    borderRadius: 10,
    marginRight: 12,
    backgroundColor: "#e2e8f0",
  },
  titleBox: { flex: 1 },
  title: { fontSize: 22, fontWeight: "700", color: "#0b1226" },
  subtitle: { fontSize: 13, color: "#6b7280", marginTop: 3 },
  inputLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  inputLabel: { fontSize: 13, fontWeight: "600", color: "#0b1226" },
  helperText: { fontSize: 11, color: "#6b7280" },
  inputRow: {
    marginTop: 8,
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    paddingHorizontal: 12,
    alignItems: "center",
    flexDirection: "row",
    height: 46,
  },
  input: {
    flex: 1,
    marginLeft: 8,
    fontSize: 15,
    height: "100%",
    color: "#0b1226", // visible star color
  },
  eyeBtn: { padding: 6 },
  rowBetween: {
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  linkText: { color: "#2563eb", fontWeight: "600" },
  submitBtn: {
    marginTop: 16,
    backgroundColor: "#0b72ff",
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
  },
  submitText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  smallRow: {
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  smallText: { color: "#6b7280" },
});
